### ISSUE TITLE
Juniper compatibility

### ISSUE THREAD

**Issue by toxinu** [adlnet-archive/Table-XBlock#1]
Hi there,

I wanted to know if `Table-XBlock` xBlock is already Juniper (Python 3 and Django 2.2) compatible and if not, is there any plan to update it for Juniper? Or are you open to contributions?

Thanks.

cc @mickmuzac

**Comment by mickmuzac** [comment]
Hello @toxinu! Thank you for your question. As project is no longer maintained by me, I'd recommend referring all questions to ADL directly: https://adlnet.gov/contact/

**Comment by toxinu** [comment]
Thanks for your answer @mickmuzac. I will try to reach them out.
